language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
install:
  - mvn -f componentlibrary-parentpom/pom.xml install -DskipTests=true
script:
  - mvn -f componentlibrary-parentpom/pom.xml test 